project/server/main/views.py
# project/server/main/views.py


from flask import render_template, Blueprint


main_blueprint = Blueprint("main", __name__)


@main_blueprint.route("/")
def home():
    return render_template("main/home.html")


@main_blueprint.route("/about/")
def about():
    return render_template("main/about.html")

project/client/templates/_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{{ config.APP_NAME }}{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="" />
    <meta name="author" content="" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <!-- styles -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen" />
    {% block css %}{% endblock %}
  </head>

  <body>
    {% include 'header.html' %}

    <div class="site-content">
      <div class="container">
        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %}
        <br />
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
              {{ message }}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %} {% endwith %}

        <!-- child template -->
        {% block content %}{% endblock %}

        <br />

        <!-- errors -->
        {% if error %}
        <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}
      </div>
    </div>

    <br /><br />

    {% include 'footer.html' %}

    <!-- scripts -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}
  </body>
</html>

project/client/templates/footer.html
<footer>
  <nav class="navbar fixed-bottom navbar-light bg-light">
    <div class="container">
      <small>
        <span
          >©
          <a href="http://mherman.org">Michael Herman</a>
        </span>
      </small>
    </div>
  </nav>
</footer>

project/client/templates/header.html
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <!-- Navbar Brand -->
    <a class="navbar-brand" href="{{ url_for('main.home') }}">{{ config.APP_NAME }}</a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Main Navigation -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.members') }}">Members</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>